import type { CountryPayrollProfile } from '../../../shared/types/payroll'

export const GHANA_PROFILE: CountryPayrollProfile = {
  countryCode: 'GH',
  countryName: 'Ghana',
  currency: 'GHS',
  lastVerified: '2025-01-01',
  effectiveDate: '2025-01-01',
  sourceNotes: 'Income Tax Act, 2015 (Act 896) as amended. PAYE brackets per GRA 2025 schedule.',
  fiscalYearStart: '01-01',
  taxYearStart: '01-01',

  taxSystem: {
    name: 'PAYE',
    period: 'monthly',
    brackets: [
      { min: 0,       max: 490,     rate: 0    },
      { min: 490,     max: 600,     rate: 5    },
      { min: 600,     max: 730,     rate: 10   },
      { min: 730,     max: 3896.67, rate: 17.5 },
      { min: 3896.67, max: 20000,   rate: 25   },
      { min: 20000,   max: 50000,   rate: 30   },
      { min: 50000,   max: null,    rate: 35   },
    ],
    minimumTax: null,
  },

  statutoryDeductions: [
    {
      id: 'ssnit_employee',
      name: 'SSNIT — Tier 1 (Employee)',
      shortCode: 'SSNIT',
      paidBy: 'employee',
      employeeRate: 5.5,
      employeeFixedAmount: null,
      employeeCap: null,
      employerRate: null,
      employerFixedAmount: null,
      employerCap: null,
      basis: 'basic',
      basisDescription: 'Basic salary',
      preTax: true,
      mandatory: true,
      mandatoryConditions: 'All formal sector employees',
      notes: 'Social Security and National Insurance Trust — Tier 1 mandatory pension.',
    },
    {
      id: 'ssnit_employer',
      name: 'SSNIT — Employer',
      shortCode: 'SSNIT-ER',
      paidBy: 'employer',
      employeeRate: null,
      employeeFixedAmount: null,
      employeeCap: null,
      employerRate: 13,
      employerFixedAmount: null,
      employerCap: null,
      basis: 'basic',
      basisDescription: 'Basic salary (13%: 8.5% to Tier 1 SSNIT, 4.5% to Tier 2)',
      preTax: false,
      mandatory: true,
      mandatoryConditions: null,
      notes: 'Employer contributes 13% of basic: 8.5% to SSNIT Tier 1, 4.5% to Tier 2.',
    },
    {
      id: 'tier3_voluntary',
      name: 'Tier 3 — Voluntary Provident Fund',
      shortCode: 'TIER3',
      paidBy: 'both',
      employeeRate: null,
      employeeFixedAmount: null,
      employeeCap: null,
      employerRate: null,
      employerFixedAmount: null,
      employerCap: null,
      basis: 'basic',
      basisDescription: 'Basic salary — voluntary, tax-deductible up to 16.5% of gross',
      preTax: true,
      mandatory: false,
      mandatoryConditions: 'Voluntary. Tax-deductible up to 16.5% of gross income.',
      notes: 'Both employee and employer can contribute. Amounts configurable per worker.',
    },
  ],

  allowanceTypes: [
    { id: 'basic',         name: 'Basic Salary',          taxable: true, partOfPensionable: true,  commonPercentageOfBasic: null, notes: null },
    { id: 'accommodation', name: 'Accommodation/Housing', taxable: true, partOfPensionable: false, commonPercentageOfBasic: null, notes: null },
    { id: 'transport',     name: 'Transport/Vehicle',     taxable: true, partOfPensionable: false, commonPercentageOfBasic: null, notes: null },
    { id: 'risk',          name: 'Risk Allowance',        taxable: true, partOfPensionable: false, commonPercentageOfBasic: null, notes: 'Common in agriculture and hazardous work' },
  ],

  taxReliefs: [
    {
      id: 'marriage_relief',
      name: 'Marriage/Responsibility Relief',
      type: 'fixed',
      value: 0,
      cap: null,
      basis: null,
      requiresDocumentation: true,
      documentationDescription: 'Marriage certificate',
      conditions: 'Married individuals',
      notes: 'This relief exists in legislation but the value has not been updated significantly. Check GRA for current amount.',
    },
  ],

  thresholds: [],
}
