import type { CountryPayrollProfile } from '../../../shared/types/payroll'

export const KENYA_PROFILE: CountryPayrollProfile = {
  countryCode: 'KE',
  countryName: 'Kenya',
  currency: 'KES',
  lastVerified: '2025-01-01',
  effectiveDate: '2025-01-01',
  sourceNotes: 'Income Tax Act (Cap. 470), Finance Act 2023 amendments. PAYE brackets as of January 2025.',
  fiscalYearStart: '07-01',
  taxYearStart: '01-01',

  taxSystem: {
    name: 'PAYE',
    period: 'monthly',
    brackets: [
      { min: 0,      max: 24000,  rate: 10   },
      { min: 24000,  max: 32333,  rate: 25   },
      { min: 32333,  max: 500000, rate: 30   },
      { min: 500000, max: 800000, rate: 32.5 },
      { min: 800000, max: null,   rate: 35   },
    ],
    minimumTax: null,
  },

  statutoryDeductions: [
    {
      id: 'nssf_employee',
      name: 'NSSF (Employee)',
      shortCode: 'NSSF',
      paidBy: 'employee',
      employeeRate: 6,
      employeeFixedAmount: null,
      employeeCap: 2160,
      employerRate: null,
      employerFixedAmount: null,
      employerCap: null,
      basis: 'gross',
      basisDescription: 'Gross salary (Tier I + Tier II, total cap KSh 2,160/month)',
      preTax: true,
      mandatory: true,
      mandatoryConditions: 'All employees in formal employment',
      notes: 'Total employee NSSF = Tier I (max KSh 1,080) + Tier II (max KSh 1,080) = max KSh 2,160/month.',
    },
    {
      id: 'nssf_employer',
      name: 'NSSF (Employer)',
      shortCode: 'NSSF-ER',
      paidBy: 'employer',
      employeeRate: null,
      employeeFixedAmount: null,
      employeeCap: null,
      employerRate: 6,
      employerFixedAmount: null,
      employerCap: 2160,
      basis: 'gross',
      basisDescription: 'Same tiers as employee',
      preTax: false,
      mandatory: true,
      mandatoryConditions: null,
      notes: 'Employer matches employee NSSF contributions.',
    },
    {
      id: 'nhif',
      name: 'NHIF / SHA',
      shortCode: 'NHIF',
      paidBy: 'employee',
      employeeRate: null,
      employeeFixedAmount: null,
      employeeCap: 1700,
      employerRate: null,
      employerFixedAmount: null,
      employerCap: null,
      basis: 'graduated',
      basisDescription: 'Graduated scale based on gross income (KSh 150 to KSh 1,700 per month)',
      preTax: false,
      mandatory: true,
      mandatoryConditions: 'All formal employees. Transitioning to Social Health Authority (SHA).',
      notes: 'Post-tax deduction using graduated scale.',
    },
    {
      id: 'housing_levy_employee',
      name: 'Housing Levy (Employee)',
      shortCode: 'HOUSING',
      paidBy: 'employee',
      employeeRate: 1.5,
      employeeFixedAmount: null,
      employeeCap: null,
      employerRate: null,
      employerFixedAmount: null,
      employerCap: null,
      basis: 'gross',
      basisDescription: 'Gross salary',
      preTax: false,
      mandatory: true,
      mandatoryConditions: 'All employees',
      notes: 'Affordable Housing Levy — employee 1.5%.',
    },
    {
      id: 'housing_levy_employer',
      name: 'Housing Levy (Employer)',
      shortCode: 'HOUSING-ER',
      paidBy: 'employer',
      employeeRate: null,
      employeeFixedAmount: null,
      employeeCap: null,
      employerRate: 1.5,
      employerFixedAmount: null,
      employerCap: null,
      basis: 'gross',
      basisDescription: 'Gross salary',
      preTax: false,
      mandatory: true,
      mandatoryConditions: 'All employers',
      notes: 'Employer matches employee housing levy.',
    },
    {
      id: 'nita',
      name: 'NITA Levy',
      shortCode: 'NITA',
      paidBy: 'employer',
      employeeRate: null,
      employeeFixedAmount: null,
      employeeCap: null,
      employerRate: null,
      employerFixedAmount: 50,
      employerCap: null,
      basis: 'custom',
      basisDescription: 'KSh 50 per employee per month (flat)',
      preTax: false,
      mandatory: true,
      mandatoryConditions: 'All employers',
      notes: 'National Industrial Training Authority levy.',
    },
  ],

  allowanceTypes: [
    { id: 'basic',     name: 'Basic Salary',       taxable: true, partOfPensionable: true,  commonPercentageOfBasic: null, notes: null },
    { id: 'housing',   name: 'Housing Allowance',  taxable: true, partOfPensionable: false, commonPercentageOfBasic: null, notes: 'Taxable unless employer provides housing directly' },
    { id: 'transport', name: 'Transport Allowance',taxable: true, partOfPensionable: false, commonPercentageOfBasic: null, notes: null },
    { id: 'leave',     name: 'Leave Allowance',    taxable: true, partOfPensionable: false, commonPercentageOfBasic: null, notes: null },
  ],

  taxReliefs: [
    {
      id: 'personal_relief',
      name: 'Personal Relief',
      type: 'fixed',
      value: 2400,
      cap: null,
      basis: null,
      requiresDocumentation: false,
      documentationDescription: null,
      conditions: 'All resident individual taxpayers',
      notes: 'Monthly personal tax relief of KSh 2,400. Deducted from computed tax, not from income.',
    },
    {
      id: 'insurance_relief',
      name: 'Insurance Relief',
      type: 'capped_percentage',
      value: 15,
      cap: 5000,
      basis: 'Life insurance, education policy, or health insurance premiums paid',
      requiresDocumentation: true,
      documentationDescription: 'Insurance premium payment receipts',
      conditions: 'Premiums paid for life, education, or health insurance policies',
      notes: 'Deducted from computed tax, not from income.',
    },
    {
      id: 'disability_relief',
      name: 'Disability Exemption',
      type: 'fixed',
      value: 150000,
      cap: null,
      basis: null,
      requiresDocumentation: true,
      documentationDescription: 'Disability certificate from NCPWD',
      conditions: 'Persons with disability registered with NCPWD',
      notes: 'Monthly income up to KSh 150,000 is exempt from tax.',
    },
  ],

  thresholds: [],
}
